import json
import os
import subprocess
import sys

import pytest
from dotenv import load_dotenv

load_dotenv()


@pytest.mark.skipif("GROQ_API_KEY" not in os.environ, reason="Requires GROQ_API_KEY")
def test_cli_integration_with_groq():
    """
    Test the CLI end-to-end to ensure the LLM integration actually returns
    explanations and summaries using the Groq API.
    """
    # Create a small dummy parquet file
    import pandas as pd
    
    df = pd.DataFrame([
        {
            "restaurant_id": "r1", "name": "Integration Test Res", "address": "123 Test St",
            "location": "Banashankari", "cuisines": ["North Indian", "Chinese"],
            "rating": 4.5, "votes": 100, "cost_for_two": 600,
            "online_order": True, "book_table": True, "url": "http://test.com"
        }
    ])
    
    # We will write it to a temporary location
    parquet_path = "tests/test_data_integration.parquet"
    df.to_parquet(parquet_path)

    try:
        # Run the CLI
        cmd = [
            sys.executable, "-m", "restaurant_reco_phase4.cli",
            "--data", parquet_path,
            "--place", "Banashankari",
            "--top-n", "1"
        ]
        
        # We need to run it in a subprocess and capture stdout
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        
        out = result.stdout.strip()
        print(f"STDOUT: {out}")
        print(f"STDERR: {result.stderr.strip()}")
        data = json.loads(out)
        
        assert "recommendations" in data
        assert len(data["recommendations"]) == 1
        
        rec = data["recommendations"][0]
        assert rec["name"] == "Integration Test Res"
        
        # This is the vital check for Phase 3!
        assert data.get("summary") is not None, "Summary should be generated by LLM"
        assert rec.get("explanation") is not None, "Explanation should be generated by LLM"
        
        # Verify it's actually text
        assert isinstance(data["summary"], str)
        assert len(data["summary"]) > 0
        assert isinstance(rec["explanation"], str)
        assert len(rec["explanation"]) > 0

    finally:
        # Clean up
        if os.path.exists(parquet_path):
            os.remove(parquet_path)
